language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install -r dev-requirements.txt
    - pip install coveralls
    - pip install -e .

script:
    - make test

after_success:
    - coveralls

notifications:
    email: false
